### ISSUE TITLE
(old) auth headers didn't work

### ISSUE THREAD

**Issue by darrentorpey** [arty-name/livejournal-export#18]
I tried running your program as instructed and it seemed to fail auth.

Then I tried the following, based on inspecting how it worked manually through my browser:
1. changed the `ljloggedin` header name to `ljprof` (keeping the same value)
2. changed the `ljmastersession` header name to `ljuniq` (keeping the same value)

-- and it worked!

I'm guessing LJ renamed these recently. A quick update to the `README.md` is probably all that's needed.

**Comment by arty-name** [comment]
Thank you for the proactive approach, Darren! 

Could you please verify the original version of the code with your cookies again? I am asking this, because just now I have copied the values `ljloggedin` and `ljmastersession` cookies into the `auth.py` file, and the download proceeded successfully. Could a typo or a mixup have been the cause of the issue you’ve faced?

**Comment by darrentorpey** [comment]
Thanks for looking into the issue, @arty-name -- love the handle btw. 

You're right that the old cookies still work. I wasn't seeing them in my dev tools but when I checked again I saw them there and I can confirm that they still work. So, nevermind!

**Comment by arty-name** [comment]
Thank you for confirming this, Darren! And for the rare compliment :blush:
